- name: add apt repository for emacs29
  apt_repository:
    repo: ppa:kelleyk/emacs
    state: present

- name: install emacs
  apt:
    autoclean: yes
    update_cache: yes
    name:
      - emacs-nox
