- name: add apt repository for emacs26
  apt_repository:
    repo: ppa:kelleyk/emacs
    state: present

- name: install packages.
  apt:
    autoclean: yes
    update_cache: yes
    name:
      - emacs26
