- name: Setup environment.
  hosts: localhost
  become: yes
  tasks:
    - name: install packages.
      apt:
        autoclean: yes
        update_cache: yes
        name:
          - zsh
          - git
          - git-lfs
          - tmux
          - wget
          - build-essential
          - software-properties-common

    - name: change shell
      command:
        "chsh {{ ansible_facts.env.USER }} -s /bin/zsh"


    - name: install emacs
      include: task/emacs.yaml
