- name: Setup environment.
  remote_user: sony-dev
  hosts: localhost
  become: yes
  tasks:
    - name: install packages.
      apt:
        autoclean: yes
        update_cache: yes
        name:
          - zsh
          - git
          - git-lfs
          - tmux
          - wget
          - build-essential
          - software-properties-common

    - name: install emacs26.
      include: task/emacs.yaml

    - name: change shell
      command:
        "chsh sony-dev -s /bin/zsh"
