- name: Setup environment.
  hosts: localhost
  become: no
  tasks:
    - name: clone toyos_env
      ansible.builtin.git:
        repo: https://github.com/yoshimasa1700/toyos_env.git
        dest: "/home/{{ ansible_facts.env.USER }}/toyos_env"
      ignore_errors: true

    - name: run setup scripts.
      command:
        "zsh /home/{{ ansible_facts.env.USER }}/toyos_env/0_setup.zsh"
      ignore_errors: true

    - name: run setup scripts.
      command:
        "zsh /home/{{ ansible_facts.env.USER }}/toyos_env/1_setup_links.zsh"
